// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdxybmnpkkdkspgxvnfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkeHlibW5wa2tka3NwZ3h2bmZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODAyNDAsImV4cCI6MjA2ODc1NjI0MH0.r2eHhFksdrFcu4OdbG0GcyjSoqhBv2EqI6gCad8jhDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});